// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: apps/grpc/protos/homepb/home.proto

package homepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Home struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RawAddress string `protobuf:"bytes,3,opt,name=rawAddress,proto3" json:"rawAddress,omitempty"`
}

func (x *Home) Reset() {
	*x = Home{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_grpc_protos_homepb_home_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Home) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Home) ProtoMessage() {}

func (x *Home) ProtoReflect() protoreflect.Message {
	mi := &file_apps_grpc_protos_homepb_home_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Home.ProtoReflect.Descriptor instead.
func (*Home) Descriptor() ([]byte, []int) {
	return file_apps_grpc_protos_homepb_home_proto_rawDescGZIP(), []int{0}
}

func (x *Home) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Home) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Home) GetRawAddress() string {
	if x != nil {
		return x.RawAddress
	}
	return ""
}

type GetHomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetHomeRequest) Reset() {
	*x = GetHomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_grpc_protos_homepb_home_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeRequest) ProtoMessage() {}

func (x *GetHomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_grpc_protos_homepb_home_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeRequest.ProtoReflect.Descriptor instead.
func (*GetHomeRequest) Descriptor() ([]byte, []int) {
	return file_apps_grpc_protos_homepb_home_proto_rawDescGZIP(), []int{1}
}

func (x *GetHomeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HomeResponse) Reset() {
	*x = HomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_grpc_protos_homepb_home_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeResponse) ProtoMessage() {}

func (x *HomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_grpc_protos_homepb_home_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeResponse.ProtoReflect.Descriptor instead.
func (*HomeResponse) Descriptor() ([]byte, []int) {
	return file_apps_grpc_protos_homepb_home_proto_rawDescGZIP(), []int{2}
}

func (x *HomeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_apps_grpc_protos_homepb_home_proto protoreflect.FileDescriptor

var file_apps_grpc_protos_homepb_home_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x04, 0x48, 0x6f, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x61, 0x77, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x48, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xa9, 0x01, 0x0a, 0x0b, 0x48, 0x6f, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x6d, 0x65, 0x12, 0x16, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x68, 0x6f, 0x6d,
	0x65, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x61,
	0x76, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x0c, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x62, 0x2e,
	0x48, 0x6f, 0x6d, 0x65, 0x1a, 0x14, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x48, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0c, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x65, 0x64, 0x77, 0x62, 0x61, 0x65, 0x7a, 0x61, 0x2f, 0x69, 0x6e, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x3b, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_apps_grpc_protos_homepb_home_proto_rawDescOnce sync.Once
	file_apps_grpc_protos_homepb_home_proto_rawDescData = file_apps_grpc_protos_homepb_home_proto_rawDesc
)

func file_apps_grpc_protos_homepb_home_proto_rawDescGZIP() []byte {
	file_apps_grpc_protos_homepb_home_proto_rawDescOnce.Do(func() {
		file_apps_grpc_protos_homepb_home_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_grpc_protos_homepb_home_proto_rawDescData)
	})
	return file_apps_grpc_protos_homepb_home_proto_rawDescData
}

var file_apps_grpc_protos_homepb_home_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apps_grpc_protos_homepb_home_proto_goTypes = []interface{}{
	(*Home)(nil),           // 0: homepb.Home
	(*GetHomeRequest)(nil), // 1: homepb.GetHomeRequest
	(*HomeResponse)(nil),   // 2: homepb.HomeResponse
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_apps_grpc_protos_homepb_home_proto_depIdxs = []int32{
	1, // 0: homepb.HomeService.GetHome:input_type -> homepb.GetHomeRequest
	0, // 1: homepb.HomeService.SaveHome:input_type -> homepb.Home
	3, // 2: homepb.HomeService.ListHomes:input_type -> google.protobuf.Empty
	0, // 3: homepb.HomeService.GetHome:output_type -> homepb.Home
	2, // 4: homepb.HomeService.SaveHome:output_type -> homepb.HomeResponse
	0, // 5: homepb.HomeService.ListHomes:output_type -> homepb.Home
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_grpc_protos_homepb_home_proto_init() }
func file_apps_grpc_protos_homepb_home_proto_init() {
	if File_apps_grpc_protos_homepb_home_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_grpc_protos_homepb_home_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Home); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_grpc_protos_homepb_home_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_grpc_protos_homepb_home_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_grpc_protos_homepb_home_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_grpc_protos_homepb_home_proto_goTypes,
		DependencyIndexes: file_apps_grpc_protos_homepb_home_proto_depIdxs,
		MessageInfos:      file_apps_grpc_protos_homepb_home_proto_msgTypes,
	}.Build()
	File_apps_grpc_protos_homepb_home_proto = out.File
	file_apps_grpc_protos_homepb_home_proto_rawDesc = nil
	file_apps_grpc_protos_homepb_home_proto_goTypes = nil
	file_apps_grpc_protos_homepb_home_proto_depIdxs = nil
}
