FROM golang:1.20 AS builder

RUN apt-get -qq update && apt-get -yqq install upx

ENV GO111MODULE=on \
CGO_ENABLED=0 \
GOOS=linux

WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

CMD ["go", "run", "main.go"]
